IF
  Detect([PC])
  Allegiance(Myself,NEUTRAL)
  Global("quest1","LOCALS",1)
THEN
  RESPONSE #10
    Wait(1)
    MoveToObject("Way1")
  RESPONSE #10
    Wait(2)
    MoveToObject("Way2")
  RESPONSE #10
    Wait(1)
    MoveToObject("Way3")
  RESPONSE #10
    Wait(2)
    MoveToObject("Way4")
  RESPONSE #10
    Wait(1)
    MoveToObject("Way5")
  RESPONSE #1
    Wait(1)
    MoveToObject("COPCUST3")
    DisplayStringHead(Myself,4590) // No more for you
    Wait(2)
END


